
# General site settings
title: GeyserMC Wiki
author: GeyserMC
description: >-
  This is the wiki for all of GeyserMC's projects.

# Url settings
baseurl: ""
url: "https://wiki.geysermc.org"

# Repository settings
repo: "https://github.com/GeyserMC/GeyserWiki"

# Build settings
markdown: kramdown
highlighter: rouge
exclude: [_site, LICENSE, README.md]

# Collections
collections:
  docs:
    output: true
    permalink: /:path/

# Front Matter Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page

  - scope:
      path: ""
      type: "pages"
    values:
      layout: default