// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // Uncomment for autogenerated sidebar
    // sidebar: [{type: 'autogenerated', dirName: '.'}],

    sidebar: {
        "Geyser Documentation": [
            {
                type: "category",
                label: "Setting up Geyser",
                items: [
                    // "geyser/setup",
                    "geyser/supported-hosting-providers",
                    "geyser/using-geyser-with-consoles",
                    "geyser/playit-gg",
                    "geyser/creating-a-startup-script"
                ]
            },
            {
                type: "category",
                label: "Common Issues",
                items: [
                    "geyser/common-issues",
                    "geyser/fixing-unable-to-connect-to-world"
                ]
            },
            {
                type: "category",
                label: "Configuring Geyser",
                items: [
                    "geyser/understanding-the-config",
                    "geyser/commands",
                    "geyser/geyser-command-line-arguments-and-system-properties"
                ]
            },
            {
                type: "category",
                label: "FAQ",
                items: [
                    "geyser/faq",
                    "geyser/anticheat-compatibility",
                    "geyser/current-limitations"
                ]
            },
            "geyser/custom-items",
            "geyser/custom-blocks",
            "geyser/custom-skulls",
            {
                type: "category",
                label: "Geyser API",
                items: [
                    "geyser/getting-started-with-the-api",
                    "geyser/api",
                    "geyser/events",
                    "geyser/forms"
                ]
            },
            "geyser/extensions",
            "geyser/global-api"
        ],
        "Floodgate Documentation": [
            "floodgate/setup",
            "floodgate/issues",
            "floodgate/faq",
            "floodgate/features",
            {
                type: "category",
                label: "Features",
                items: [
                    "floodgate/features",
                    "floodgate/commands",
                    "floodgate/features"
                ]
            },
            {
                type: "category",
                label: "Floodgate API",
                items: [
                    "floodgate/player",
                    "geyser/forms"
                ]
            },
            {
                type: "category",
                label: "Linking",
                items: [
                    "floodgate/linking",
                    "floodgate/linking"
                ]
            }
        ],
        "Other": [
            "other/geyseroptionalpack",
            "other/hurricane",
            "other/geyserconnect",
            "other/community-geyser-projects",
            "other/test-server",
            "other/developer-guide",
            "other/discord-bot-usage"
        ]
    }
};

module.exports = sidebars;
