import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  geyserSidebar: [
    'geyser/setup',
    'geyser/common-issues',
    'geyser/understanding-the-config',
    'geyser/faq',
    'geyser/custom-items',
    'geyser/custom-blocks',
    'geyser/custom-skulls',
    'geyser/api',
    'geyser/extensions',
    'geyser/global-api'
  ],

  floodgateSidebar: [
    'floodgate/setup',
    'floodgate/issues',
    'floodgate/faq',
    'floodgate/features',
    'floodgate/api',
    'floodgate/linking'
  ],

  otherSidebar: [
    'other/geyseroptionalpack',
    'other/hurricane',
    'other/geyserconnect',
    'other/community-geyser-projects',
    'other/test-server',
    'other/developer-guide',
    'other/discord-bot-usage'
  ]
};

export default sidebars;
